### ISSUE TITLE
Using CustomCSS in cases other than the "compose" view (eg. preview)

### ISSUE THREAD

**Issue by maciejsokol** [GrantEdwards/CustomCSS#3]
Hi,
I would be very grateful if the settings from CustomCSS would be reflected in the email preview as well.
I am getting a newsletter I care about that is completely unreadable. For some reason, the newsletter author limits the displayed text to two lines. Of course, there is a full description in the HTML code.
I wrote a CSS rule that displays all the text and it works great, but unfortunately, I have to open this email in the "compose" view. A more convenient option would be to use custom CSS rules already in the preview.
Is there an easy way to implement such an option?

**Comment by GrantEdwards** [comment]
I'm afraid I don't know how to do that. But, I thought that there were other, existing methods to apply user stylesheets to the display of e-mails in Thunderbird.  Do any of these help?

[https://github.com/Aris-t2/CustomCSSforTb](https://github.com/Aris-t2/CustomCSSforTb)
[https://devnodes.in/blog/misc/thunderbird-mail-theme-customize/](https://devnodes.in/blog/misc/thunderbird-mail-theme-customize/)

Or perhaps this?

[https://support.mozilla.org/en-US/questions/1320156](https://support.mozilla.org/en-US/questions/1320156)

**Comment by GrantEdwards** [comment]
I think that another way to do what you want is using a message display script:

[https://webextension-api.thunderbird.net/en/102/messageDisplayScripts.html](https://webextension-api.thunderbird.net/en/102/messageDisplayScripts.html)

**Comment by maciejsokol** [comment]
I checked the trick you sent in the first link - it worked perfectly ([CustomCSSforTb](https://github.com/Aris-t2/CustomCSSforTb)).
Thank you for your quick response and for your help.
In my opinion, we can end this topic as a not-planned solution since it is already covered by other methods/tricks, and I was just goofy :)
